In [2]:
from google.colab import files
uploaded = files.upload()

Saving charity_data.csv to charity_data.csv

In [3]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import io

# Import and read the charity_data.csv
import pandas as pd
application_df = pd.read_csv(io.BytesIO(uploaded['charity_data.csv']))
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN','NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts<200].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
clean_classification = classification_counts[classification_counts>1]
clean_classification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts<200].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1197
C7000      777
C1700      287
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [12]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 52)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_features = X_train_scaled.shape[1]
hidden_layer1 = 10
hidden_layer2 = 20
hidden_layer3 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1, input_dim=number_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                460

 dense_1 (Dense)             (None, 20)                220

 dense_2 (Dense)             (None, 30)                630

 dense_3 (Dense)             (None, 1)                 31

=================================================================
Total params: 1,341
Trainable params: 1,341
Non-trainable params: 0
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train, validation_split=0.17, epochs=100)

Epoch 1/100
668/668 [==============================] - 3s 3ms/step - loss: 0.5960 - accuracy: 0.7014 - val_loss: 0.5604 - val_accuracy: 0.7286
Epoch 2/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5581 - accuracy: 0.7279 - val_loss: 0.5567 - val_accuracy: 0.7295
Epoch 3/100
668/668 [==============================] - 2s 4ms/step - loss: 0.5531 - accuracy: 0.7308 - val_loss: 0.5561 - val_accuracy: 0.7289
Epoch 4/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5507 - accuracy: 0.7304 - val_loss: 0.5578 - val_accuracy: 0.7311
Epoch 5/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7306 - val_loss: 0.5559 - val_accuracy: 0.7289
Epoch 6/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5478 - accuracy: 0.7319 - val_loss: 0.5513 - val_accuracy: 0.7305
Epoch 7/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5462 - accuracy: 0.7332 - val_loss: 0.5523 - val_accuracy: 0.7314
Epoch 8/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7341 - val_loss: 0.5536 - val_accuracy: 0.7311
Epoch 9/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7328 - val_loss: 0.5535 - val_accuracy: 0.7289
Epoch 10/100
668/668 [==============================] - 3s 5ms/step - loss: 0.5444 - accuracy: 0.7346 - val_loss: 0.5532 - val_accuracy: 0.7300
Epoch 11/100
668/668 [==============================] - 4s 5ms/step - loss: 0.5443 - accuracy: 0.7345 - val_loss: 0.5518 - val_accuracy: 0.7305
Epoch 12/100
668/668 [==============================] - 3s 5ms/step - loss: 0.5435 - accuracy: 0.7332 - val_loss: 0.5528 - val_accuracy: 0.7311
Epoch 13/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7341 - val_loss: 0.5503 - val_accuracy: 0.7325
Epoch 14/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7344 - val_loss: 0.5543 - val_accuracy: 0.7311
Epoch 15/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7351 - val_loss: 0.5523 - val_accuracy: 0.7314
Epoch 16/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7359 - val_loss: 0.5554 - val_accuracy: 0.7298
Epoch 17/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7339 - val_loss: 0.5539 - val_accuracy: 0.7321
Epoch 18/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5420 - accuracy: 0.7355 - val_loss: 0.5530 - val_accuracy: 0.7327
Epoch 19/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7351 - val_loss: 0.5532 - val_accuracy: 0.7311
Epoch 20/100
668/668 [==============================] - 2s 4ms/step - loss: 0.5414 - accuracy: 0.7350 - val_loss: 0.5529 - val_accuracy: 0.7295
Epoch 21/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7355 - val_loss: 0.5535 - val_accuracy: 0.7327
Epoch 22/100
668/668 [==============================] - 4s 6ms/step - loss: 0.5417 - accuracy: 0.7345 - val_loss: 0.5538 - val_accuracy: 0.7291
Epoch 23/100
668/668 [==============================] - 5s 8ms/step - loss: 0.5411 - accuracy: 0.7353 - val_loss: 0.5540 - val_accuracy: 0.7222
Epoch 24/100
668/668 [==============================] - 4s 6ms/step - loss: 0.5407 - accuracy: 0.7356 - val_loss: 0.5538 - val_accuracy: 0.7220
Epoch 25/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7333 - val_loss: 0.5525 - val_accuracy: 0.7330
Epoch 26/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7357 - val_loss: 0.5517 - val_accuracy: 0.7339
Epoch 27/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7365 - val_loss: 0.5529 - val_accuracy: 0.7195
Epoch 28/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7361 - val_loss: 0.5532 - val_accuracy: 0.7309
Epoch 29/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7348 - val_loss: 0.5524 - val_accuracy: 0.7295
Epoch 30/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7370 - val_loss: 0.5541 - val_accuracy: 0.7291
Epoch 31/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7353 - val_loss: 0.5521 - val_accuracy: 0.7327
Epoch 32/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7363 - val_loss: 0.5504 - val_accuracy: 0.7343
Epoch 33/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7370 - val_loss: 0.5533 - val_accuracy: 0.7332
Epoch 34/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7353 - val_loss: 0.5518 - val_accuracy: 0.7343
Epoch 35/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7355 - val_loss: 0.5567 - val_accuracy: 0.7197
Epoch 36/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7371 - val_loss: 0.5531 - val_accuracy: 0.7316
Epoch 37/100
668/668 [==============================] - 2s 4ms/step - loss: 0.5399 - accuracy: 0.7370 - val_loss: 0.5524 - val_accuracy: 0.7321
Epoch 38/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7360 - val_loss: 0.5548 - val_accuracy: 0.7318
Epoch 39/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5391 - accuracy: 0.7370 - val_loss: 0.5523 - val_accuracy: 0.7318
Epoch 40/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7370 - val_loss: 0.5554 - val_accuracy: 0.7302
Epoch 41/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7367 - val_loss: 0.5552 - val_accuracy: 0.7291
Epoch 42/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7364 - val_loss: 0.5538 - val_accuracy: 0.7302
Epoch 43/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5388 - accuracy: 0.7379 - val_loss: 0.5547 - val_accuracy: 0.7311
Epoch 44/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7363 - val_loss: 0.5518 - val_accuracy: 0.7309
Epoch 45/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7374 - val_loss: 0.5524 - val_accuracy: 0.7323
Epoch 46/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7384 - val_loss: 0.5528 - val_accuracy: 0.7263
Epoch 47/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7370 - val_loss: 0.5560 - val_accuracy: 0.7316
Epoch 48/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7381 - val_loss: 0.5549 - val_accuracy: 0.7316
Epoch 49/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7370 - val_loss: 0.5520 - val_accuracy: 0.7318
Epoch 50/100
668/668 [==============================] - 2s 4ms/step - loss: 0.5383 - accuracy: 0.7371 - val_loss: 0.5558 - val_accuracy: 0.7307
Epoch 51/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7360 - val_loss: 0.5521 - val_accuracy: 0.7327
Epoch 52/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7368 - val_loss: 0.5538 - val_accuracy: 0.7316
Epoch 53/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7377 - val_loss: 0.5538 - val_accuracy: 0.7307
Epoch 54/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7377 - val_loss: 0.5579 - val_accuracy: 0.7259
Epoch 55/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7378 - val_loss: 0.5520 - val_accuracy: 0.7325
Epoch 56/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5376 - accuracy: 0.7361 - val_loss: 0.5519 - val_accuracy: 0.7337
Epoch 57/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7384 - val_loss: 0.5531 - val_accuracy: 0.7314
Epoch 58/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.7381 - val_loss: 0.5532 - val_accuracy: 0.7321
Epoch 59/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7374 - val_loss: 0.5528 - val_accuracy: 0.7309
Epoch 60/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7382 - val_loss: 0.5531 - val_accuracy: 0.7318
Epoch 61/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7370 - val_loss: 0.5518 - val_accuracy: 0.7334
Epoch 62/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5371 - accuracy: 0.7385 - val_loss: 0.5541 - val_accuracy: 0.7309
Epoch 63/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7373 - val_loss: 0.5540 - val_accuracy: 0.7325
Epoch 64/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7374 - val_loss: 0.5519 - val_accuracy: 0.7316
Epoch 65/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7379 - val_loss: 0.5541 - val_accuracy: 0.7307
Epoch 66/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7376 - val_loss: 0.5551 - val_accuracy: 0.7305
Epoch 67/100
668/668 [==============================] - 3s 5ms/step - loss: 0.5370 - accuracy: 0.7386 - val_loss: 0.5520 - val_accuracy: 0.7309
Epoch 68/100
668/668 [==============================] - 3s 5ms/step - loss: 0.5371 - accuracy: 0.7384 - val_loss: 0.5523 - val_accuracy: 0.7311
Epoch 69/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7383 - val_loss: 0.5528 - val_accuracy: 0.7305
Epoch 70/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7378 - val_loss: 0.5545 - val_accuracy: 0.7341
Epoch 71/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7387 - val_loss: 0.5592 - val_accuracy: 0.7302
Epoch 72/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7391 - val_loss: 0.5540 - val_accuracy: 0.7316
Epoch 73/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7393 - val_loss: 0.5535 - val_accuracy: 0.7307
Epoch 74/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7380 - val_loss: 0.5591 - val_accuracy: 0.7307
Epoch 75/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7385 - val_loss: 0.5538 - val_accuracy: 0.7316
Epoch 76/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7378 - val_loss: 0.5533 - val_accuracy: 0.7321
Epoch 77/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7399 - val_loss: 0.5547 - val_accuracy: 0.7234
Epoch 78/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7384 - val_loss: 0.5567 - val_accuracy: 0.7337
Epoch 79/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7372 - val_loss: 0.5512 - val_accuracy: 0.7309
Epoch 80/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7388 - val_loss: 0.5547 - val_accuracy: 0.7323
Epoch 81/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7388 - val_loss: 0.5547 - val_accuracy: 0.7309
Epoch 82/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7400 - val_loss: 0.5535 - val_accuracy: 0.7309
Epoch 83/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7383 - val_loss: 0.5532 - val_accuracy: 0.7298
Epoch 84/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7379 - val_loss: 0.5553 - val_accuracy: 0.7327
Epoch 85/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7394 - val_loss: 0.5593 - val_accuracy: 0.7286
Epoch 86/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7391 - val_loss: 0.5564 - val_accuracy: 0.7327
Epoch 87/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7393 - val_loss: 0.5552 - val_accuracy: 0.7302
Epoch 88/100
668/668 [==============================] - 3s 5ms/step - loss: 0.5358 - accuracy: 0.7392 - val_loss: 0.5548 - val_accuracy: 0.7330
Epoch 89/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7385 - val_loss: 0.5538 - val_accuracy: 0.7323
Epoch 90/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7377 - val_loss: 0.5532 - val_accuracy: 0.7321
Epoch 91/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7377 - val_loss: 0.5540 - val_accuracy: 0.7323
Epoch 92/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7386 - val_loss: 0.5565 - val_accuracy: 0.7327
Epoch 93/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7383 - val_loss: 0.5526 - val_accuracy: 0.7323
Epoch 94/100
668/668 [==============================] - 3s 4ms/step - loss: 0.5356 - accuracy: 0.7387 - val_loss: 0.5530 - val_accuracy: 0.7307
Epoch 95/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7384 - val_loss: 0.5525 - val_accuracy: 0.7300
Epoch 96/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7394 - val_loss: 0.5527 - val_accuracy: 0.7327
Epoch 97/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7389 - val_loss: 0.5540 - val_accuracy: 0.7327
Epoch 98/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7394 - val_loss: 0.5541 - val_accuracy: 0.7318
Epoch 99/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7383 - val_loss: 0.5560 - val_accuracy: 0.7307
Epoch 100/100
668/668 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7386 - val_loss: 0.5567 - val_accuracy: 0.7318

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5664 - accuracy: 0.7251 - 414ms/epoch - 2ms/step
Loss: 0.566413164138794, Accuracy: 0.7251312136650085

In [18]:
# Export our model to HDF5 file
nn.save('Models/AlphabetSoupCharity_Optimization.h5')